name: Build Docker for Release
run-name: Build Docker Images

on: 
  push:
    tags:
      - '*'

jobs:
  TEST:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print tag
        run: echo "tag=${GITHUB_REF#refs/tags/}"